package:
  name: iniparser
  version: 4.2.5
  epoch: 0
  description: "C library for parsing 'INI-style' files"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - doxygen
      - graphviz
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ndevilla/iniparser
      tag: v${{package.version}}
      expected-commit: 19e0ad6c37440ba52313e10c6e148dfb9ab417f6

  - uses: cmake/configure
    with:
      opts: |
        -DBUILD_DOCS=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "iniparser-dev"
    description: "headers for iniparser"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - iniparser
    test:
      pipeline:
        - uses: test/pkgconf

  - name: "iniparser-doc"
    description: "iniparser documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc/iniparser "${{targets.subpkgdir}}"/usr/share
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: ndevilla/iniparser
    strip-prefix: v
    use-tag: true
    tag-filter: v
