package:
  name: lazygit
  version: "0.45.2"
  epoch: 2
  description: simple terminal UI for git commands
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jesseduffield/lazygit
      tag: v${{package.version}}
      expected-commit: c03b89227092b852d50015d289a7c6d8c69811c5

  - uses: go/build
    with:
      packages: .
      ldflags: |
        -X main.version=${{package.version}}
        -X main.commit=$(git rev-parse HEAD)
        -X main.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        -X main.buildSource=wolfiRelease
      output: lazygit

update:
  enabled: true
  github:
    identifier: jesseduffield/lazygit
    strip-prefix: v

test:
  pipeline:
    - runs: |
        lazygit --version
        lazygit --help
