package:
  name: libassuan
  version: 3.0.1
  epoch: 1
  description: IPC library used by some GnuPG related software
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libgpg-error-dev
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: c8f0f42e6103dea4b1a6a483cb556654e97302c7465308f58363778f95f194b1
      uri: https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-${{package.version}}.tar.bz2

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libassuan-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libassuan
        - libgpg-error-dev
    description: libassuan dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: libassuan-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: libassuan manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  release-monitor:
    identifier: 1559
