package:
  name: llvm-lld-19
  version: 19.1.0
  epoch: 0
  description: The LLVM Linker
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - llvm-lld=19

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-19
      - cmake
      - curl
      - git
      - libedit-dev
      - llvm-19
      - llvm-19-dev
      - llvm-cmake-19
      - llvm-libunwind-dev
      - samurai
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8d125e7513735c57adbdd1bbce59ff2d5844c2bf64a00ff94fe1c04b941ca2b2
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{package.version}}/lld-${{package.version}}.src.tar.xz

  - runs: |
      cmake -B build -G Ninja -Wno-dev \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_MODULE_PATH=/usr/lib/llvm-${{vars.major-version}}/share/cmake/Modules \
        -DLLVM_COMMON_CMAKE_UTILS="/usr/lib/llvm-${{vars.major-version}}/share/cmake" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DBUILD_SHARED_LIBS=OFF \
        -DLLVM_INCLUDE_TESTS=OFF \
        -DLLD_BUILT_STANDALONE=ON \
        -DLLVM_CONFIG=/usr/lib/llvm-${{vars.major-version}}/bin/llvm-config \
        -DLLVM_INCLUDE_DIRS=/usr/lib/llvm-${{vars.major-version}}/include

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR=${{targets.destdir}} cmake --install build

subpackages:
  - name: ${{package.name}}-static
    pipeline:
      - uses: split/static

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    description: llvm-lld dev

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    use-tag: true
    tag-filter: llvmorg-19.1.
    strip-prefix: llvmorg-
