package:
  name: rancher-fleet
  version: "0.11.3"
  epoch: 2
  description: Deploy workloads from Git to large fleets of Kubernetes clusters
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4aada7ee85153474c29a6f90f7bde23b747aeee7
      repository: https://github.com/rancher/fleet
      tag: v${{package.version}}

subpackages:
  - name: ${{package.name}}-agent
    pipeline:
      - uses: go/build
        with:
          ldflags: |
            -X github.com/rancher/fleet/pkg/version.GitCommit=$(git rev-parse HEAD)
            -X github.com/rancher/fleet/pkg/version.Version=${{package.version}}
          output: fleetagent
          packages: ./cmd/fleetagent/main.go
    test:
      pipeline:
        - runs: |
            fleetagent --version | grep ${{package.version}}

update:
  enabled: true
  github:
    identifier: rancher/fleet
    strip-prefix: v
