package:
  name: rocksdb
  version: 9.6.1
  epoch: 0
  description: "A library that provides an embeddable, persistent key-value store for fast storage."
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2
      - libtbb
      - liburing-dev
      - lz4-dev
      - python3
      - snappy
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/facebook/rocksdb.git
      tag: v${{package.version}}

  - uses: autoconf/make
    with:
      opts: shared_lib

  - uses: autoconf/make-install
    with:
      opts: install-shared

  - uses: strip

update:
  enabled: true
  github:
    identifier: facebook/rocksdb
    use-tag: true
    strip-prefix: v
