package:
  name: ruby3.4-webrick
  version: 1.9.0
  epoch: 0
  description: WEBrick is an HTTP server toolkit that can be configured as an HTTPS server, a proxy server, and a virtual-host server.
  copyright:
    - license: Ruby
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby-${{vars.rubyMM}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby${{vars.rubyMM}}-rubygems
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev
      - ruby3.4-rubygems

vars:
  gem: webrick

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 516db777a61e269266fcd85cc9c866e4fef37aef
      repository: https://github.com/ruby/webrick
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: ruby/webrick
    strip-prefix: v

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
