package:
  name: ruby3.4-elasticsearch-api
  version: 8.16.0
  epoch: 0
  description: |
    Ruby API for Elasticsearch. See the `elasticsearch` gem for full integration.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-multi_json

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev
      - ruby3.4-rubygems

vars:
  gem: elasticsearch-api

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/elastic/elasticsearch-ruby.git
      tag: v${{package.version}}
      expected-commit: 2acbce702ecdc3c7f8e8116e81a76a836f75c6f0

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: elastic/elasticsearch-ruby
    strip-prefix: v
    use-tag: true
    tag-filter: v

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
