package:
  name: ruby3.4-console
  version: 1.29.0
  epoch: 0
  description: Beautiful logging for Ruby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-fiber-annotation
      - ruby${{vars.rubyMM}}-fiber-local
      - ruby${{vars.rubyMM}}-fiber-storage
      - ruby${{vars.rubyMM}}-json
      - ruby-${{vars.rubyMM}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev
      - ruby3.4-rubygems

vars:
  gem: console

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ebd30eca2797b448a791d2e4149b1f1b56db7207
      repository: https://github.com/socketry/console
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

test:
  pipeline:
    - runs: ruby -e "require 'console'"

update:
  enabled: true
  github:
    identifier: socketry/console
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
