package:
  name: ruby3.4-protocol-http2
  version: 0.20.0
  epoch: 0
  description: A low level implementation of the HTTP/2 protocol.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-protocol-hpack
      - ruby${{vars.rubyMM}}-protocol-http
      - ruby-${{vars.rubyMM}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev
      - ruby3.4-rubygems

vars:
  gem: protocol-http2

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 76a6cda55ac572af57ae7d87e12dc297930c9d42
      repository: https://github.com/socketry/protocol-http2
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/protocol-http2
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
