package:
  name: ruby3.4-rubygems
  version: 3.5.16
  epoch: 0
  description: rubygems

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang
      - coreutils # I want real rm
      - execline
      - git
      - ruby-3.4-bootstrap
      - ruby-3.4-bootstrap-dev
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rubygems/rubygems.git
      tag: v${{package.version}}
      expected-commit: f49d3d48c9aeb96f2251aaaa07192f0ffff381f0

  - runs: |
      set -x
      ruby setup.rb --destdir="${{targets.destdir}}" --prefix="/usr" --verbose

  - runs: |
      rm -rf --verbose \
      "${{targets.destdir}}/usr/gems" \
      "${{targets.destdir}}/usr/lib/bundler.rb" \
      "${{targets.destdir}}/usr/lib/bundler.rb" \
      "${{targets.destdir}}/usr/lib/bundler" \
      "${{targets.destdir}}/usr/specifications" \
      ${{targets.destdir}}/usr/bin/bundle*

vars:
  gem: gem
