package:
  name: ruby-3.4
  version: 3.4.0
  epoch: 0
  description: "the Ruby programming language"
  copyright:
    - license: Ruby
    - license: BSD-2-Clause
  dependencies:
    provides:
      - ruby=${{package.full-version}}
    runtime:
      - glibc
      - gmp
      - libgcc
      - openssl
      - yaml
      - zlib

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - coreutils
      - gdbm-dev
      - glibc-dev
      - gmp-dev
      - graphviz
      - libffi-dev
      - libxcrypt-dev
      - linux-headers
      - openssf-compiler-options
      - openssl-dev
      - pkgconf
      - readline-dev
      - ruby-3.4-bootstrap
      - rust
      - tk-dev
      - yaml-dev
      - zlib-dev

vars:
  prefix: /usr

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: underscore-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ruby/ruby
      tag: v${{vars.underscore-package-version}}_preview2
      expected-commit: 32c733f57bb91e22972319ee63eac9521d954ebc

  - name: Generate and Configure
    runs: |
      ./autogen.sh
      ./configure \
         --prefix=${{vars.prefix}} \
         --sysconfdir=/etc \
         --enable-shared \
         --disable-rpath \
         --enable-pthread \
         --enable-mkmf-verbose \
         --enable-yjit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  - runs: |
      set -x
      RUBYWILD="$(echo ${{package.version}} | cut -d. -f-2).*"
      RUBYDIR=${{targets.destdir}}${{vars.prefix}}/lib/ruby/$RUBYWILD rm -rf ${RUBYDIR}/bundler rm ${RUBYDIR}/bundler.rb
      GEMDIR=${{targets.destdir}}${{vars.prefix}}/lib/ruby/gems/$RUBYWILD rm -rf ${GEMDIR}/gems/bundler-* rm ${GEMDIR}/specifications/default/bundler-*.gemspec
      rm -rf ${{targets.destdir}}/usr/bin/bundle \ ${{targets.destdir}}/usr/bin/bundler
      rm -rf ${{targets.destdir}}/usr/lib/ruby/${{package.version}}*/bundler*

  - runs: |
      set -x

      rm -rf --verbose ${{targets.destdir}}/usr/lib/ruby/gems/${{package.version}}*/cache
      while read -r gem ; do
        echo $gem
        rm -rf --verbose ${{targets.destdir}}/usr/lib/ruby/gems/${{package.version}}*/gems/${gem}*
        rm -rf --verbose ${{targets.destdir}}/usr/lib/ruby/specifications/${gem}-*.gemspec
        rm -rf --verbose ${{targets.destdir}}/usr/lib/ruby/gems/${{package.version}}*/specifications/${gem}*.gemspec
        rm -rf --verbose ${{targets.destdir}}/usr/lib/ruby/gems/${{package.version}}*/specifications/default/${gem}*.gemspec
      done < standard_gems
      while read -r bin ; do
         echo $bin
         rm -rf --verbose ${{targets.destdir}}/usr/bin/${bin}
         rm -rf --verbose ${{targets.destdir}}/usr/bin/${bin}.lock
         rm -rf --verbose ${{targets.destdir}}/usr/share/man/man1/${bin}.1
      done < standard_gems_bins

subpackages:
  - name: "ruby-3.4-doc"
    description: "ruby documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/ri "${{targets.subpkgdir}}"/usr/share/

  - name: "ruby-3.4-dev"
    description: "ruby development headers"
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  version-transform:
    - match: "_"
      replace: .
  github:
    identifier: ruby/ruby
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v3_4_

test:
  pipeline:
    - runs: |
        ruby --version | grep ${{package.version}}

        cat <<EOF >> /tmp/hello.rb
        puts("Hello Wolfi!")
        EOF

        ruby /tmp/hello.rb
        ruby --help
    - name: Test bundled binaries are absent
      runs: |
        ls /usr/bin | grep 'racc|rake|rbi|erb|gem' || exit 0 && exit 1
